# Generated by Django 6.0 on 2026-05-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examattempt_student_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
